# Generated by Django 3.2.9 on 2022-04-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('the_social_network', '0002_auto_20211111_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideoStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=100)),
                ('videoTime', models.CharField(db_index=True, max_length=100)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_social_network.statement')),
            ],
        ),
    ]
